### ISSUE TITLE
Can't run dev or build

### ISSUE THREAD

**Issue by remjx** [ielvisd/BoostVue#1]
Hi, npm/pnpm install completes successfully. However I get this error when I run `npm run dev`. Tried on Ubuntu 20 and MacOS 13 with Node 18. 

```
$ npm run dev 

> boost-vue@0.0.0 dev
> vite

failed to load config from /home/remjx/workspace/BoostVue/vite.config.js
error when starting dev server:
Error: Cannot find module 'unocss/vite'
Require stack:
- /home/remjx/workspace/BoostVue/vite.config.js
- /home/remjx/workspace/BoostVue/node_modules/vite/dist/node/chunks/dep-2285ba4f.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/remjx/workspace/BoostVue/vite.config.js:32:27)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at _require.extensions.<computed> [as .js] (file:///home/remjx/workspace/BoostVue/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:63071:24)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
```

**Comment by ielvisd** [comment]
Thanks for the heads up! I wasn't seeing this issue locally when I launched the repo. Should be working now. 👍
